package com.example.musicapps.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.musicapps.database.TTrack;

import com.example.musicapps.database.TTrackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tTrackDaoConfig;

    private final TTrackDao tTrackDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tTrackDaoConfig = daoConfigMap.get(TTrackDao.class).clone();
        tTrackDaoConfig.initIdentityScope(type);

        tTrackDao = new TTrackDao(tTrackDaoConfig, this);

        registerDao(TTrack.class, tTrackDao);
    }
    
    public void clear() {
        tTrackDaoConfig.clearIdentityScope();
    }

    public TTrackDao getTTrackDao() {
        return tTrackDao;
    }

}
