package com.example.musicapps.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TTRACK".
 */
@Entity
public class TTrack {

    @Id
    private Long id;
    private long TrackId;

    @NotNull
    private String TrackName;

    @NotNull
    private String ArtisName;
    private int IsFavorite;
    private int IsLoading;

    @Generated
    public TTrack() {
    }

    public TTrack(Long id) {
        this.id = id;
    }

    @Generated
    public TTrack(Long id, long TrackId, String TrackName, String ArtisName, int IsFavorite, int IsLoading) {
        this.id = id;
        this.TrackId = TrackId;
        this.TrackName = TrackName;
        this.ArtisName = ArtisName;
        this.IsFavorite = IsFavorite;
        this.IsLoading = IsLoading;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTrackId() {
        return TrackId;
    }

    public void setTrackId(long TrackId) {
        this.TrackId = TrackId;
    }

    @NotNull
    public String getTrackName() {
        return TrackName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTrackName(@NotNull String TrackName) {
        this.TrackName = TrackName;
    }

    @NotNull
    public String getArtisName() {
        return ArtisName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setArtisName(@NotNull String ArtisName) {
        this.ArtisName = ArtisName;
    }

    public int getIsFavorite() {
        return IsFavorite;
    }

    public void setIsFavorite(int IsFavorite) {
        this.IsFavorite = IsFavorite;
    }

    public int getIsLoading() {
        return IsLoading;
    }

    public void setIsLoading(int IsLoading) {
        this.IsLoading = IsLoading;
    }

}
