package com.example.musicapps.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TTRACK".
*/
public class TTrackDao extends AbstractDao<TTrack, Long> {

    public static final String TABLENAME = "TTRACK";

    /**
     * Properties of entity TTrack.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TrackId = new Property(1, long.class, "TrackId", false, "TRACK_ID");
        public final static Property TrackName = new Property(2, String.class, "TrackName", false, "TRACK_NAME");
        public final static Property ArtisName = new Property(3, String.class, "ArtisName", false, "ARTIS_NAME");
        public final static Property IsFavorite = new Property(4, int.class, "IsFavorite", false, "IS_FAVORITE");
        public final static Property IsLoading = new Property(5, int.class, "IsLoading", false, "IS_LOADING");
    }


    public TTrackDao(DaoConfig config) {
        super(config);
    }
    
    public TTrackDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TTRACK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TRACK_ID\" INTEGER NOT NULL ," + // 1: TrackId
                "\"TRACK_NAME\" TEXT NOT NULL ," + // 2: TrackName
                "\"ARTIS_NAME\" TEXT NOT NULL ," + // 3: ArtisName
                "\"IS_FAVORITE\" INTEGER NOT NULL ," + // 4: IsFavorite
                "\"IS_LOADING\" INTEGER NOT NULL );"); // 5: IsLoading
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TTRACK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TTrack entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTrackId());
        stmt.bindString(3, entity.getTrackName());
        stmt.bindString(4, entity.getArtisName());
        stmt.bindLong(5, entity.getIsFavorite());
        stmt.bindLong(6, entity.getIsLoading());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TTrack entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTrackId());
        stmt.bindString(3, entity.getTrackName());
        stmt.bindString(4, entity.getArtisName());
        stmt.bindLong(5, entity.getIsFavorite());
        stmt.bindLong(6, entity.getIsLoading());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TTrack readEntity(Cursor cursor, int offset) {
        TTrack entity = new TTrack( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // TrackId
            cursor.getString(offset + 2), // TrackName
            cursor.getString(offset + 3), // ArtisName
            cursor.getInt(offset + 4), // IsFavorite
            cursor.getInt(offset + 5) // IsLoading
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TTrack entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTrackId(cursor.getLong(offset + 1));
        entity.setTrackName(cursor.getString(offset + 2));
        entity.setArtisName(cursor.getString(offset + 3));
        entity.setIsFavorite(cursor.getInt(offset + 4));
        entity.setIsLoading(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TTrack entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TTrack entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TTrack entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
